"""Bake the scaler constants + int8 threshold into a C header.

Run after convert_tflite.py. Split out from the converter because the firmware
needs these even if you're iterating on the sketch without retraining.
"""

import json
import sys
from pathlib import Path

art = Path(sys.argv[1] if len(sys.argv) > 1 else "artifacts")
out = Path(sys.argv[2] if len(sys.argv) > 2 else "firmware/nano33ble/scaler_data.h")
meta = json.loads((art / "threshold.json").read_text())

if "threshold_int8" not in meta:
    sys.exit("no threshold_int8 in threshold.json -- run convert_tflite first")

mean, scale = meta["scaler"]["mean"], meta["scaler"]["scale"]


def arr(name, vals):
    # Chunks already end in a comma -- join with newline only, or you get
    # a double comma and a compiler error.
    body = "\n  ".join(
        ", ".join(f"{v:.8g}f" for v in vals[i : i + 4]) + "," for i in range(0, len(vals), 4)
    )
    return f"static const float {name}[N_FEATURES] = {{\n  {body}\n}};"


out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "\n".join(
        [
            "// Auto-generated by scripts/export_scaler.py -- do not edit by hand.",
            "// Regenerate with: make firmware-model",
            "",
            "#ifndef SCALER_DATA_H",
            "#define SCALER_DATA_H",
            "",
            '#include "features.h"',
            "",
            f"// Calibrated against the int8 model, target FPR {meta['target_fpr']:.1%}.",
            f"#define THRESHOLD_INT8 {meta['threshold_int8']:.8g}f",
            f"#define TRAINED_FEATURE_VERSION {meta.get('feature_version', 3)}",
            "",
            arr("kFeatureMean", mean),
            "",
            arr("kFeatureScale", scale),
            "",
            "#endif  // SCALER_DATA_H",
            "",
        ]
    )
)
print(f"wrote {out}  (threshold_int8={meta['threshold_int8']:.5f})")
